server:
  port: 8888
  servlet:
    context-path: /
limit:
  minMoney: 1
  maxMoney: 10
  desc: 最低${limit.minMoney}最高${limit.maxMoney}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/business
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  thymeleaf:
    mode: HTML
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:F:/upload
mybatis:
  mapper-locations: classpath*:com/geng/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
business:
  imageHost: http://localhost:8888/static/
  #springboot规定静态资源放在static或者template(template要用控制器跳转)
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.geng.dao: debug